### ISSUE TITLE
Fractional BPM support?

### ISSUE THREAD

**Issue by m13253** [gomidi/mid#1]
From the documentation I found that you describe BPM in `uint32`.

```go
type Reader struct {
    Msg struct {
        Meta struct {
            // Tempo is called for the tempo (change) message
            Tempo func(p Position, bpm uint32)
        }
    }
}
```

However the MIDI specification records tempo in Microseconds-per-Beat, this allows fractional BPM (e.g. 62.5 BPM = 960000 usPB) and allows accurate long-term synchronization.

How do I read and write songs with fractional BPM in gomidi?

Thanks.

Reference (_The Complete MIDI 1.0 Detailed Specification_, ver. 96.1):
> FF 51 03 tttttt
> Set Tempo, in microseconds per MIDI quarter-note
>
> This event indicates a tempo change. Another way of putting "microseconds per quarter-note" is "24ths of a microsecond per MIDI clock". Representing tempos as time per beat instead of beat per time allows absolutely exact long-term synchronization with a time-based sync protocol such as SMPTE time code or MIDI time code. This amount of accuracy provided by this tempo resolution allows a four-minute piece at 120 beats per minute to be accurate within 500 usec at the end of the piece. Ideally, these events should only occur where MIDI clocks would be located — this convention is intended to guarantee, or at least increase the likelihood, of compatibility with other synchronization devices so that a time signature/tempo map stored in this format may easily be transferred to another device.

**Comment by metakeule** [comment]
@m13253 
Thanks for bringing this up!

Well, it seems that I haven't put enough thoughts into this. Frankly I never felt the need for fractional BPM.
But I see the issue now and will have to fix it throughout gomidi/mid and gomidi/midi.

BPM is a more musical term than microseconds per beat, so I am looking for a musical term.
Maybe MilliBPM, so that 1000 MilliBPM = 1 BPM. Would that be fine enough?

**Comment by metakeule** [comment]
Another way would be to expose "microseconds per quarter-note" as a type and add helper methods to get and set it based on a BPM (rounded) and/or MilliBPM (rounded) and directly (full resolution).

**Comment by m13253** [comment]
> BPM is a more musical term than microseconds per beat, so I am looking for a musical term.
> Maybe MilliBPM, so that 1000 MilliBPM = 1 BPM. Would that be fine enough?

My personal suggestion is to add a `bpm float64` function. If we want to maintain API stability we can rename the new function:
```go
TempoFloat func(p Position, bpm float64)
```

> Another way would be to expose "microseconds per quarter-note" as a type and add helper methods to get and set it based on a BPM (rounded) and/or MilliBPM (rounded) and directly (full resolution).

I agree that it is always good to have at least one method to access the raw data. Otherwise, something would lose when we just simply copy data from one file to another file. (But at least we have the `[]byte` interface so that's actually okay.)

**Comment by metakeule** [comment]
fractional BPM support is now integrated into the underlying https://github.com/gomidi/midi library in a backwards compatible way.

Now will be integrated into this lib as a breaking change (we give no guarantees about a stable API here).
